server:
  port: 9000
management:
  server:
    port: 9001
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  application:
    name: helloworld
  profiles:
    active: sit
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    bus:
      id: ${spring.application.name}:${spring.profiles.active}:${server.port}
      enabled: true
    refresh:
      enabled: true
  kafka:
    bootstrap-servers: http://localhost:9093